---
apiVersion: v1
kind: Namespace
metadata:
  name: app-ingress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-ingress
  namespace: app-ingress
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-ingress
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - ingresses
  - services
  verbs:
  - get
  - list
  - delete
  - create
  - update
  - patch
- apiGroups:
  - "extensions"
  resources:
  - ingresses
  verbs:
  - get
  - list
  - delete
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watch-app-1
  namespace: epinio-workloads
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-ingress
subjects:
- kind: ServiceAccount
  name: app-ingress
  namespace: app-ingress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ingress
  namespace: app-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app-ingress
  template:
    metadata:
      labels:
        name: app-ingress
    spec:
      serviceAccountName: app-ingress
      containers:
        - name: app-ingress
          imagePullPolicy: Always
          image: "quay.io/mudler/eirinix-ingress:v0.2"
          env:
            - name: NAMESPACE
              value: "epinio-workloads"
            - name: LABELS
              value: '{ "eirinix-ingress": "true", "kubernetes.io/ingress.class": "traefik" }'
            - name: ANNOTATIONS
              value: '{ "traefik.ingress.kubernetes.io/router.entrypoints": "websecure",
                "traefik.ingress.kubernetes.io/router.tls": "true" }'
            - name: ENABLE_TLS
              value: "true"
