name: outside_pr

on:
  pull_request:
    branches: [ main ]
    types: [ labeled ]

jobs:
  build:
    runs-on: self-hosted
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get all git tags
        run: git fetch --prune --unshallow --tags
      - name: Setup Go for Building
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.7'
      - name: Setup Ginkgo Test Framework
        run: go get -u github.com/onsi/ginkgo/ginkgo
      - name: Lint Epinio
        run: make lint
      - name: Cache Tools
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/tools
          key: ${{ runner.os }}-tools
      - name: Install Tools
        run: make tools-install
      - name: Add Tools to PATH
        run: |
          echo "`pwd`/output/bin" >> $GITHUB_PATH
      - name: Run unit tests
        run: make test
      - name: Acceptance tests
        env:
          REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          GINKGO_NODES=6 make test-acceptance
