name: Release-pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch Branch
        id: branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }} | grep origin/main)
          branch=${raw##*/}
          echo "::set-output name=BRANCH_NAME::$branch"
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.7'
      - name: Build Epinio
        if: steps.branch.outputs.BRANCH_NAME == 'main'
        run: |
          make build-all-small
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CFCIBOT_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CFCIBOT_DOCKERHUB_PASSWORD }}
      - name: Build Epinio images
        if: steps.branch.outputs.BRANCH_NAME == 'main'
        run: |
          make build-images
      - name: Create CHECKSUMS
        if: steps.branch.outputs.BRANCH_NAME == 'main'
        run: ( cd dist ; sha256sum -b epinio* > SHA256SUM.txt )

      - name: Get current tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/heads\//}

      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
          name: "Epinio Release ${{ steps.get_tag.outputs.TAG }} 🌈"
          tag: ${{ steps.get_tag.outputs.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Epinio
        uses: softprops/action-gh-release@v1
        if: steps.branch.outputs.BRANCH_NAME == 'main'
        with:
          files: ./dist/*
          body_path: ./CHANGELOG.md
          prerelease: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
